Repository LemontechSA/limoneno, pull requests merged in 2019-11, with the labels that each got.

#15 Hotfix: Se corrige reemplazo de tipos de entidades
  frontend/src/modules/workspace/components/project-content/project-tag.tsx
Labels: ToReview, bug

#22 Add asdf support
  backend/.tool-versions
  frontend/.tool-versions
Labels: dependencies

#14 CT-2390 / Corección de espacios en textos de documentos
  backend/app/api/versions/v1/dataset_items.rb
  backend/app/api/versions/v1/projects.rb
  backend/app/models/dataset_item.rb
  backend/app/services/dataset_service.rb
  backend/db/migrate/20191112201442_add_raw_text_to_dataset_items.rb
  backend/db/schema.rb
  backend/test/factories/dataset_items.rb
  backend/test/models/dataset_item_test.rb
  backend/test/models/project_test.rb
  backend/test/services/dataset_service_test.rb
Labels: Mergeable
